<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
?>
/** 
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 */ 
 

/* ***************
TOPBAR
*************** */
.ohyes-topbar-inner {
padding: 10px;
}
.ohyes-topbar-search{
margin-top: -3px;
}

.ohyes-topbar-search input{
  background-color:#515151;
  border-color:#111;
  border-radius: 20px;
  padding: 10px;
  outline: none;
 
  color:#ccc;
  height: 30px;
}
.ohyes-topbar-search input[type=text]:focus{
  background-color:#fff;
  border-color:#111;
  color:#000;
  border-radius: 20px;
}
.ohyestheme-topbar-username {
  font-weight: bold;
  font-size: 18px;
}
.ohyestheme-topbar-username:hover {
opacity: 0.5;
}
.elgg-menu-topbar-alt img {
 border-radius:10px;
}

.elgg-menu-topbar-alt .elgg-border-plain {
 border:none;
}
/**************************************
 Topbar ohyestopmenu 
**************************************/
.ohyestopmenu {
    /* display: block; */
    display: inline-block;
    margin-right: 3px;
    margin-left: 20px;
    position: relative;
    z-index: 101;
}

.ohyestopmenu .ohyestopmenu_button {
    cursor: pointer;
    width: auto;
    display: inline-block;
    font-weight: bold;
    color: #777;
    text-decoration: none !important;
}

.ohyestopmenu:target .ohyestopmenu_button {
    color: white;
}

.ohyestopmenu .ohyestopmenu_close { display: none }

.ohyestopmenu:target .ohyestopmenu_close { display: inline-block }

.ohyestopmenu:target .ohyestopmenu_open { display: none }


.arrow {
    display: inline-block;
    width: 0px;
    height: 0px;
    border-top: 5px solid #D1D1D1;
    border-right: 5px solid transparent;
    border-left: 5px solid transparent;
}

.ohyestopmenu:target .arrow {
    border-top: 5px solid #fff;
    border-right: 5px solid transparent;
    border-left: 5px solid transparent;
}

.ohyestopmenu .ohyestopmenu_content {
    display: none;
    position: absolute;
    border: 1px solid #777;
    padding: 0px;
	min-width: 100px;
    background: white;
    margin: 0;
}


.ohyestopmenu:target .ohyestopmenu_content { display: block }

.ohyestopmenu .ohyestopmenu_content li {
    list-style: none;
    margin-left: 0px;
    line-height: 16px;
    border-top: 1px solid #FFF;
    border-bottom: 1px solid #FFF;
    margin-top: 2px;
    margin-bottom: 2px;
}

.ohyestopmenu .ohyestopmenu_content li:hover {
 border-top-color: #999;
border-bottom-color: #999;
background: #CCC;
}

.ohyestopmenu .ohyestopmenu_content li a {
    display: block;
    padding: 2px 7px;
    padding-right: 15px;
    color: black;
    font-weight:bold;
    text-decoration: none !important;
    white-space: nowrap;
}

.ohyestopmenu .ohyestopmenu_content li:hover a {
    color: white;
    text-decoration: none !important;
}

.ohyestopmenu .ohyestopmenu_content li img {
    height: 14px;
    margin-top: 1px;
    margin-bottom: 1px;
    float: left;
    margin-right: 5px;
    border: none;
}	
.elgg-menu-item-topbar-ohyestheme-contents {
   margin-top: -10px;
}
.ohyes-theme-home-icon {
		background:url("<?php echo elgg_get_site_url();?>mod/OhYesTheme/images/home.png") no-repeat;
		width:39px;
		height:32px;
}
.ohyes-theme-photos-icon {
		background:url("<?php echo elgg_get_site_url();?>mod/OhYesTheme/images/photos.png") no-repeat;
		width:39px;
		height:32px;
	}
.ohyes-theme-link-icon {
		background:url("<?php echo elgg_get_site_url();?>mod/OhYesTheme/images/link.png") no-repeat;
		width:39px;
		height:32px;
}
.ohyes-theme-link-groups {
		background:url("<?php echo elgg_get_site_url();?>mod/OhYesTheme/images/groups.png") no-repeat;
		width:39px;
		height:32px;
}
.ohyes-theme-link-files {
		background:url("<?php echo elgg_get_site_url();?>mod/OhYesTheme/images/files.png") no-repeat;
		width:39px;
		height:32px;
}
.ohyes-theme-link-pages {
		background:url("<?php echo elgg_get_site_url();?>mod/OhYesTheme/images/pages.png") no-repeat;
		width:39px;
		height:32px;
}
.ohyes-theme-link-blog {
		background:url("<?php echo elgg_get_site_url();?>mod/OhYesTheme/images/blog.png") no-repeat;
		width:39px;
		height:32px;
}
.ohyes-theme-link-messages {
		background:url("<?php echo elgg_get_site_url();?>mod/OhYesTheme/images/messages.png") no-repeat;
		width:39px;
		height:32px;
}  
.ohyes-page-menuitems{
		display:inline-block;
}
.ohyes-page-menuitem {
		margin-left: 20px;
	    cursor:pointer;

}
.ohyes-page-menuitem :hover{
		    opacity: 0.9;	
}
.ohyes-page-menuitem p{
		color: #636363;
}
/*******************************
Ohyes River
************************************/
.ohyes_river_page {
  width:900px;
  margin:0 auto;
}
#ohyes_river .elgg-body {
	display: block;
	width: auto;
	word-wrap: break-word;
	overflow: hidden;
	
	zoom:1;
    background:#fff;
	*overflow:visible;
    padding: 30px;
    border: 1px solid #DADADA;
}
.ohyes_river_page .elgg-avatar-medium > a > img,
.ohyes-river-icon{
   width:60px;
   border-radius:45px;
   height:60px;
}

.ohyes_river_page .elgg-image {
   float: left;
   padding: 20px;
   margin-top: 20px;
}

.ohyes_river_page .elgg-list-river {
  border:none;
}

.ohyes_river_page .elgg-list > li {
  border:none;  
}

.ohyes_river_page  .elgg-list-river > li {
  border:none;
}
.ohyes_river_page  .elgg-river-responses .elgg-item {
 background-color:#fff;
}
.ohyes_river_page .elgg-avatar-tiny img {
   border-radius:20px;
}
.ohyes_river_page .elgg-menu-item-delete {
  background-color:#fff;
}
.elgg-river-summary a {
font-weight:bold;
}
.elgg-river-summary a:hover {
text-decoration:none;
}
.elgg-river-item form {
  background-color:#fff;
  margin-left: 210px;
}
/****************************************
  Ohyes Footer
******************************************/
.ohyes-theme-footer {
	border-top: 1px solid #CCC;
    min-height: 50px;
    margin-left: 30px;
    width: 900px;
    margin-top: 20px;
    padding:10px;
}
.ohyes-theme-footer a{
	text-decoration:none;
}

/***************************************
 OhYes PROFILE
****************************************/
.ohyes-profile-infos .elgg-avatar-large img {
   border-radius:100px;
}

#ohyes-profile-container .elgg-list-river {
  border:none;
}

#ohyes-profile-container .elgg-list > li {
  border:none;  
}

#ohyes-profile-container  .elgg-river-responses .elgg-item {
 background-color:#fff;
}

#ohyes-profile-container .elgg-menu-item-delete {
  background-color:#fff;
}
.ohyes-profile-menu .elgg-menu li a  {
   float:right;
   margin-top: 10px;
   margin-left: 10px;
   margin-right: 10px;
}

.ohyes-admin-menu a {
color:#DA1E1E;
text-decoration:none;
}
.elgg-menu-item-admin a{
    color:#DA1E1E;
}
.ohyes-profile-infos{
	display:inline-table;
}
.ohyes-profile-infos .elgg-body{
display: block;
width: auto;
word-wrap: break-word;
overflow: hidden;
zoom: 1;
background: #FFF;
padding: 30px;
border:none;
}
.ohyes-profile-infos li {
	display:block;
}
.ohyes-profile-info-details{
margin-top: -160px;
width: 450px;
margin-left: -30px;
}
.ohyes-profile-info-name{
	color: #08C;
font-size: 30px;
}
#ohyes-profile-container .elgg-avatar-small > a > img {
 border-radius:40px;	
 margin-top: 20px;
 margin-right: 20px;
}

#ohyes-profile-activity .elgg-body{
	display: block;
	width: auto;
	word-wrap: break-word;
	overflow: hidden;
	
	/* IE 6, 7 */
	zoom:1;
    background:#fff;
	*overflow:visible;
    padding: 30px;
    border-bottom: 1px solid #DADADA;
}
.ohyes-profile-cover {
 height: 250px;
 background-size: cover;
 background-repeat: no-repeat;
}
.ohyes-profile-cover-container {
  background:#E0E0E0;
  border: 1px solid #eee;
  margin-left: 63px;
  height:250px;
}
/******************************************
 Subtitle
*******************************************/
.ohyes-subtitle-blog {
 margin-left:20px;
 }
/******************************************
 Posts
******************************************/
.ohyes-blog-post {
 margin-left:20px;
}  
/***************************************
 Buttons
***************************************/
.ohyes-buttons-set {
 width:100px;
 font-weight:bold;
}
/*****************************************
  OhYesTheme Page
******************************************/
.ohyes-theme-page{
 background:#eee;
}

.ohyes-theme-header {
  padding: 20px;
  margin-left: 100px;
  margin-top:50px;
  width:750px;
}
.ohyes-theme-centered {
  width:900px; 
  margin:0 auto;
}
