<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/ 
 
$menu = $vars['menu'];
foreach($menu as $item){
?>
              <span class="ohyes-page-menuitem">
                  <div class="ohyes-page-menuitems">
                  <a href="<?php echo $item['url'];?>">
                      <div class="<?php echo $item['image_class'];?>" title="<?php echo $item['title'];?>"></div>
                    </a>  
                   </div>
                </span>
                
<?php } ?>                
                
               