<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 

include_once(elgg_get_plugins_path().'OhYesTheme/classes/ohyestheme.class.php');

elgg_register_event_handler('init', 'system', 'ohyes_theme');

$CONFIG->OHYESTHEMEcontext = array();
global $OhYesTheme;
if (!isset($OhYesTheme)) {
	$OhYesTheme = new stdClass;
}

/**
* Theme Startup Settings
* @access system
* @return null;
*/
function ohyes_theme(){
   //cover actions register
   if(OhYesTheme::canCover()){
   $action_path = elgg_get_plugins_path() . 'OhYesTheme/actions/';
   elgg_register_action('ohyes/addcover', "$action_path/upload/cover.php");
   elgg_register_action('ohyes/deletecover', "$action_path/delete/cover.php");
   }
   //unregister some of menus
   elgg_register_event_handler('pagesetup', 'system', 'ohyestheme_unregister_menus');
   
   //register some menus
   elgg_register_event_handler('pagesetup', 'system', 'ohyestheme_register_menus');
   
   //register profile menus
   elgg_register_event_handler('pagesetup', 'system', 'ohyestheme_profile');  
   
   //modify messages
   elgg_unregister_event_handler('pagesetup', 'system', 'messages_notifier');
   
   //Unregister some of pages;
   elgg_unregister_page_handler('blog', 'blog_page_handler');
   elgg_unregister_page_handler('activity');
   elgg_unregister_page_handler('profile', 'profile_page_handler');
   
   //Register pages
   elgg_register_page_handler('activity', 'ohyes_activity_page_handler');
   elgg_register_page_handler('blog', 'ohyes_blog_page_handler');
   elgg_register_page_handler('profile', 'ohyes_profile_page_handler');
   elgg_register_page_handler('ohyes', 'ohyes_page_handler');
   
   //add a fancybox
   elgg_register_js('jquery.fancybox', 'vendors/jquery/fancybox/jquery.fancybox-1.3.4.pack.js', 'head');
   elgg_register_css('jquery.fancybox', 'vendors/jquery/fancybox/jquery.fancybox-1.3.4.css', 'head');

   //register ohyes css
   elgg_register_simplecache_view('css/ohyestheme/ohyes');
   $ohyescss = elgg_get_simplecache_url('css', 'ohyestheme/ohyes');
   elgg_register_css('ohyestheme.css', $ohyescss, 1);
 
   //header menu setup
   elgg_register_event_handler('pagesetup', 'system', 'ohyestheme_header_menu');  
 
   //register js for theme
   elgg_register_simplecache_view('js/ohyestheme/ohyes');
   $ohyesjs = elgg_get_simplecache_url('js', 'ohyestheme/ohyes');
   elgg_register_js('ohyestheme.js', $ohyesjs);

   //load js and css for theme
      OhYesTheme::loadCSS();
	  OhYesTheme::loadJs();
 
}
/**
* Theme Menu Managment
* @Required Event Handler 'pagesetup'
* @access system
* @return null;
*/

function ohyestheme_unregister_menus(){
    elgg_unregister_menu_item('topbar', 'administration');
	elgg_unregister_menu_item('topbar', 'usersettings'); 
	elgg_unregister_menu_item('topbar', 'profile');
	elgg_unregister_menu_item('topbar', 'elgg_logo');
}
/**
* Theme header menu management
* @Required Event Handler 'pagesetup'
* @access system
* @return null;
*/
function ohyestheme_header_menu(){
$OhyesTheme = new OhYesTheme;
$user = elgg_get_logged_in_user_entity();
$OhyesTheme->register_menu_item('header', array(
											   'url' => elgg_get_site_url(),
											   'title' => elgg_echo('ohyes:home'),
											   'image_class' => 'ohyes-theme-home-icon',
											     ));	

if(elgg_is_active_plugin('tidypics')){											
$OhyesTheme->register_menu_item('header', array(
											   'url' => elgg_get_site_url().'photos/all',
											   'title' => elgg_echo('ohyes:photos'),
											   'image_class' => 'ohyes-theme-photos-icon',
											  ));
}

if(elgg_is_active_plugin('blog')){											
$OhyesTheme->register_menu_item('header', array(
											   'url' => elgg_get_site_url().'blog/all',
											   'title' => elgg_echo('ohyes:blog'),
											   'image_class' => 'ohyes-theme-link-blog',
											  ));
}

if(elgg_is_active_plugin('bookmarks')){
$OhyesTheme->register_menu_item('header', array(
											   'url' => elgg_get_site_url().'bookmarks/all',
											   'title' => elgg_echo('ohyes:bookmarks'),
											   'image_class' => 'ohyes-theme-link-icon',
											  ));
}
if(elgg_is_active_plugin('file')){
$OhyesTheme->register_menu_item('header', array(
											   'url' => elgg_get_site_url().'file/all',
											   'title' => elgg_echo('ohyes:file'),
											   'image_class' => 'ohyes-theme-link-files',
											  ));
}
if(elgg_is_active_plugin('pages')){
$OhyesTheme->register_menu_item('header', array(
											   'url' => elgg_get_site_url().'pages/all',
											   'title' => elgg_echo('ohyes:pages'),
											   'image_class' => 'ohyes-theme-link-pages',
											  ));
}
if(elgg_is_active_plugin('groups')){
$OhyesTheme->register_menu_item('header', array(
											   'url' => elgg_get_site_url().'groups/all',
											   'title' => elgg_echo('ohyes:groups'),
											   'image_class' => 'ohyes-theme-link-groups',
											  ));
}
if(elgg_is_active_plugin('messages') && elgg_is_logged_in()){
$OhyesTheme->register_menu_item('header', array(
											   'url' => elgg_get_site_url()."messages/inbox/{$user->username}",
											   'title' => elgg_echo('ohyes:messages'),
											   'image_class' => 'ohyes-theme-link-messages',
											  ));
}
}
/**
* Theme profile menu management
* @Required Event Handler 'pagesetup'
* @access system
* @return null;
*/
function ohyestheme_profile(){
$fetchfriends = new ElggUser;
$user = elgg_get_page_owner_entity();	
if(elgg_is_admin_logged_in() && elgg_get_logged_in_user_entity()->guid !==  $user->guid){
  elgg_register_menu_item('ohyes/profile', array(
			'name' => 'admin',
			'href' => '#ohyes-profile-admin',
			'id' => 'ohyes-profile-menu-admin',
			'text' =>  elgg_echo('ohyes:admin:menu'),
			'class' => 'ohyes-buttons-set elgg-button-submit',
   ));
 		
}
if(elgg_is_logged_in()){
    if(elgg_get_logged_in_user_entity()->guid !==  $user->guid){
		
         if ($user instanceof ElggUser && $user->isFriend()) {
	            $friendadd = "action/friends/remove?friend={$user->guid}";
			    $friendadd_text = elgg_echo('ohyes:un:friend');
               }
          else {
				$friendadd = "action/friends/add?friend={$user->guid}";
				$friendadd_text = elgg_echo('ohyes:add:friend');
           }	
				
     elgg_register_menu_item('ohyes/profile', array(
	     		'name' => 'addfriend',
	    		'href' => $friendadd,
	    		'text' =>  $friendadd_text,
	    		'is_action' => true,
		    	'class' => 'ohyes-buttons-set elgg-button-submit'
      ));
  
    elgg_register_menu_item('ohyes/profile', array(
	    		'name' => 'messageuser',
		    	'href' => "messages/compose?send_to={$user->guid}",
			    'text' =>  elgg_echo('ohyes:message'),
		    	'class' => 'ohyes-buttons-set elgg-button-submit',

      ));
	}
}
if(elgg_get_logged_in_user_entity()->guid ==  $user->guid){
    elgg_register_menu_item('ohyes/profile', array(
	    		'name' => 'profile_edit',
		    	'href' => "profile/$user->username/edit",
			    'text' =>  elgg_echo('profile:edit'),
		    	'class' => 'ohyes-buttons-set elgg-button-submit',

      ));
   if(OhYesTheme::canCover()){	
   elgg_register_menu_item('ohyes/profile', array(
	    		'name' => 'profile_cover',
		    	'href' => "#ohyes-theme-addcover",
				'id' => 'ohyes-profile-cover',
			    'text' =>  elgg_echo('ohyes:cover:add'),
		    	'class' => 'ohyes-buttons-set elgg-button-submit',

      ));
   }
}
 elgg_register_menu_item('ohyes/profile', array(
			'name' => 'info',
			'href' => '#ohyes-profile-info',
			'id' => 'ohyes-profile-about',
			'text' =>  elgg_echo('ohyes:about'),
			'class' => 'ohyes-buttons-set elgg-button-submit',
   ));
 

}
/**
* Theme menu management
* @Required Event Handler 'pagesetup'
* @access system
* @return null;
*/
function ohyestheme_register_menus(){
	$is_user = elgg_get_logged_in_user_entity();
    if(elgg_is_admin_logged_in()){
	elgg_register_menu_item('topbar', array(
			'name' => 'administration',
			'href' => 'admin',
			'text' => elgg_echo('admin'),
			'priority' => 100,
			'section' => 'alt',
		));
	}
	
	elgg_register_menu_item('topbar', array(
			'name' => 'usettings_ohyestheme',
			'href' => "settings/user/{$is_user->username}",
			'text' =>  elgg_echo('settings'),
			'priority' => 500,
			'section' => 'alt',
		));
	
	elgg_register_menu_item('topbar', array(
			'name' => 'topbar_ohyestheme_user',
			'href' => "profile/{$is_user->username}",
			'text' =>  "$is_user->name",
			'class' => 'ohyestheme-topbar-username',
			'style' => 'font-size:18px;',
			'priority' => 1,
   ));
	if ($is_user) {
	 elgg_register_menu_item('topbar', array(
			'name' => 'profile',
			'href' => $is_user->getURL(),
			'text' => elgg_view('output/img', array(
				'src' => $is_user->getIconURL('topbar'),
				'alt' => $is_user->name,
				'title' => elgg_echo('profile'),
				'class' => 'elgg-border-plain elgg-transition',
			)),
			'priority' => 1,
			'link_class' => 'elgg-topbar-avatar',
		   'section' => 'alt',

		));
	
	}
	
	if(!elgg_is_logged_in()){
	  elgg_register_menu_item('topbar', array(
			'name' => 'topbar_ohyestheme_user',
			'href' => elgg_get_site_url(),
			'text' =>  elgg_get_site_entity()->name,
			'class' => 'ohyestheme-topbar-username',
			'style' => 'font-size:18px;',
			'priority' => 1,
      ));	
	}
	elgg_register_menu_item('topbar', array(
			'name' => 'topbar_ohyestheme_contents',
			'href' => '#',
			'text' =>  elgg_view_menu('site'),
			'priority' => 3,
   ));
    
   elgg_register_menu_item('topbar', array(
        'name' => 'search',
        'href' => false,
        'text' => elgg_view('ohyes/theme/search'),
        'priority' => 2
   ));
   
if (elgg_is_logged_in()) {
		$class = "elgg-icon elgg-icon-mail-alt";
		$text = "<span class='$class'></span>";
		$tooltip = elgg_echo("messages");
		
		$num_messages = (int)messages_count_unread();
		if ($num_messages != 0) {
			$text .= "<span class=\"messages-new\">$num_messages</span>";
			$tooltip .= " (" . elgg_echo("messages:unreadcount", array($num_messages)) . ")";
		}

		elgg_register_menu_item('topbar', array(
			'name' => 'messages',
			'href' => 'messages/inbox/' . elgg_get_logged_in_user_entity()->username,
			'text' => $text,
			'priority' => 600,
			'title' => $tooltip,
		));
}


}
/**
* Get User Cover photo
* @Required Page Handler 'ohyes_page_handler'
* @access system
* @return page;
*/
function ohyes_page_handler($page){
	$base_dir = elgg_get_plugins_path() . 'OhYesTheme/pages/theme/';
	if (!isset($page[0])) {
		$page = array('cover');
	}
	  if(empty($page[1]) || $page[2] !== md5($page[1])){
	     exit('error');	
	   }
	    switch ($page[0]) {
		case "cover":
		    $user = $page[1];
			include "$base_dir/cover.php";
			break;
			
		default:
			return false;
	}
	return true;
}
include_once(elgg_get_plugins_path().'OhYesTheme/lib/ohyestheme.setcontext.php');

