<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/ 
 ?>
var OhYesTheme = OhYesTheme ||{}; 

OhYesTheme.HideTopMenu = function(){
  $(".ohyestopmenu_content").hide();
  $("#ohyestopmenu_hide").attr('id', "ohyestopmenu");
};
  
jQuery(document).ready(function() {
      $("#ohyes-profile-about").fancybox();
      $("#ohyes-profile-menu-admin").fancybox();
      $("#ohyes-profile-cover").fancybox();
      
      $("#ohyestopmenu").click(function () {
        $(".ohyestopmenu_content").show();
		      $("#ohyestopmenu").attr('OnClick', "OhYesTheme.HideTopMenu();");
		      $("#ohyestopmenu").attr('id', "ohyestopmenu_hide");
      });
});
