<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/ 
 ?>
  
jQuery(document).ready(function() {
      $("#ohyes-profile-about").fancybox();
      $("#ohyes-profile-menu-admin").fancybox();
      $("#ohyes-profile-cover").fancybox();

});

