<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
*/ 
 
/**
 * Elgg river image
 *
 * Displayed next to the body of each river item
 *
 * @uses $vars['item']
 */

$subject = $vars['item']->getSubjectEntity();

if (elgg_in_context('widgets')) {
	echo elgg_view_entity_icon($subject, 'tiny');
} elseif(elgg_in_context('activity')) {
	echo elgg_view('ohyes/theme/activity_icon', array('user' => $subject));
} else {
	echo elgg_view_entity_icon($subject, 'small');
}
