<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 
	
	$form = elgg_view("input/file",array(
		"internalname"=> "ohyes_cover"
	)).'<br />';
	
	$form .= elgg_view('input/submit', array(
	 'value' => elgg_echo('save')
	 )).'&nbsp;';
	if(OhYesTheme::isCover(elgg_get_logged_in_user_entity()->guid)){
	$url = elgg_add_action_tokens_to_url("action/ohyes/deletecover");
    $form .= '<a href="'.$url.'" class="elgg-button elgg-button-submit">Remove</a>';
	}
	$form .= elgg_view('input/securitytoken');
	
    echo $form;
