<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 

echo '<h3>Manage Profile Cover</h3>';
echo elgg_view('input/dropdown', array(
      'name' =>
      'params[ohyes_theme_cover]',
      'value' => $vars['entity']->ohyes_theme_cover,
      'options_values' => array(1 => 'Enable', 
								0 => 'Disable'
								)
	  ));	
echo '<p></p>';