<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 

$user = elgg_get_page_owner_entity();
$icon = elgg_view('ohyes/theme/profile_icon', array(
													'user' => $user, 
													'image_size' => 'large', 
													'hover' => false, 
													'pic_class' => 'ohyes-profile-picture'
													));

$menu = elgg_trigger_plugin_hook('register', "menu:user_hover", array(
																	  'entity' => $user), array());
$builder = new ElggMenuBuilder($menu);
$menu = $builder->getMenu();
$actions = elgg_extract('action', $menu, array());
$admin = elgg_extract('admin', $menu, array());

$admin_links = '';
if (elgg_is_admin_logged_in() && elgg_get_logged_in_user_guid() != elgg_get_page_owner_guid()) {
	$text = elgg_echo('admin:options');

$admin_links .= '<ul class="ohyes-admin-menu">';
	foreach ($admin as $menu_item) {
		$admin_links .= elgg_view('navigation/menu/elements/item', array(
																		 'item' => $menu_item
																		 ));
	}
	$admin_links .= '</ul>';	
}
$content_menu = elgg_view_menu('owner_block', array(
	'entity' => elgg_get_page_owner_entity(),
	'class' => 'profile-content-menu',
));

$profile_menu = elgg_view_menu('ohyes/profile');
$options['subject_guid'] = elgg_get_page_owner_guid();
$river_profile = elgg_list_river($options);
$profile_details = elgg_view('profile/details');

$cover_form = elgg_view_form("ohyes/addcover", array(
	   'method' => 'post', 
	   'enctype' => 'multipart/form-data' ,
	 ));

$profile_cover = OhYesTheme::coverUrl($user->guid);
if(OhYesTheme::isCover($user->guid) && OhYesTheme::canCover()){
  $cover = ' 
  <div id="ohyes-profile-container" class="ohyes-profile-cover-container">
    <div class="ohyes-profile-cover" style="background:url(\''.$profile_cover.'\') no-repeat;background-size: cover;"></div>
  </div>';
} 
else {
  $cover = '';       	
}
$profile =  <<<HTML
   $cover
<div id="ohyes-profile-container" style="background:#fff;border: 1px solid #eee;margin-left: 63px">
  <span class="ohyes-profile-menu"> 
        $profile_menu
       <span class="ohyes-profile-infos">
           <div class="" style="margin-top: 50px;margin-left: 80px;">
               $icon
            </div>
        </span>

<span class="ohyes-profile-infos" style="  margin-left: 300px;margin-top: -200px;width: 610px;">
	<h2 class="ohyes-profile-info-name"> $user->name </h2>
       $user->description 
</span>

</div>
<div id="ohyes-profile-container">
         <div id="ohyes-profile-activity">
             $river_profile
         </div>

</div>

<div  style="display:none;">
   <div id="ohyes-profile-info">
       $profile_details
   </div>
</div>

<div style="display:none;">
    <div id="ohyes-profile-admin">
        $admin_links
    </div>
</div>
<div style="display:none;">
   <div id="ohyes-theme-addcover">
    $cover_form  
    </div>
</div>

HTML;
echo $profile;