<?php
/**
 * Ohyes Theme
 * @website Link: https://github.com/lianglee/OhYesTheme
 * @Package Ohyes
 * @subpackage Theme
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2014.
 * @ide The Code is Generated by Liang Lee php IDE.
 */ 

gatekeeper();
action_gatekeeper();
$delete = new OhYesTheme;
if($delete->UnlinkCover(elgg_get_logged_in_user_entity())){
 system_message(elgg_echo('ohyes:theme:cover:removed'));													
 forward(REFERER);	
}
else {
 system_message(elgg_echo('ohyes:theme:cover:remove:error'));													
 forward(REFERER);	
}